<?php

namespace Database\Seeders;

use App\Models\Animal;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $animals = [
            ['Chó', 'Affenpinscher'],
            ['Chó', 'Thợ săn quý tộc (Afghan Hound)'],
            ['Chó', 'Airedale Terrier'],
            ['Chó', 'Alaskan Klee Kai Toy'],
            ['Chó', 'Alaskan Klee Kai Miniature'],
            ['Chó', 'Alaskan Klee Kai Standard'],
            ['Chó', 'tuyết kéo xe (Alaskan Malamute)'],
            ['Chó', 'Alsatian'],
            ['Chó', 'American Bulldog'],
            ['Chó', 'American Hairless Terrier'],
            ['Chó', 'American Pit Bull Terrier (Pit Bull)'],
            ['Chó', 'American Staffordshire Terrier'],
            ['Chó', 'American Water Spaniel'],
            ['Chó', 'Anatolian Shepherd'],
            ['Chó', 'Appenzeller Sennenhunde'],
            ['Chó', 'Ariegeois'],
            ['Chó', 'Artois Hound'],
            ['Chó', 'Australian Black and Tan Hound'],
            ['Chó', 'Australian Cattle Dog'],
            ['Chó', 'Australian Kelpie'],
            ['Chó', 'chăn cừu Úc (Australian Shepherd Dog)'],
            ['Chó', 'Australian Pinscher'],
            ['Chó', 'Australian Terrier'],
            ['Chó', 'Azawakh'],
            ['Chó', 'Barbet'],
            ['Chó', 'Basenji'],
            ['Chó', 'Basset Artesien Normand'],
            ['Chó', 'Basset Bleu De Gascogne'],
            ['Chó', 'Basset Fauve De Bretagne'],
            ['Chó', 'Basset Hound'],
            ['Chó', 'Beagle'],
            ['Chó', 'Bearded Collie'],
            ['Chó', 'Beauceron'],
            ['Chó', 'Bedlington Terrier'],
            ['Chó', 'Belgian Malinois'],
            ['Chó', 'Belgian Sheepdog'],
            ['Chó', 'Belgian Tervuren'],
            ['Chó', 'Bergamasco'],
            ['Chó', 'Berger Picard'],
            ['Chó', 'Bernese Mountain Dog'],
            ['Chó', 'Bichon Frise'],
            ['Chó', 'Black Russian Terrier'],
            ['Chó', 'Bloodhound'],
            ['Chó', 'Bluetick Coonhound'],
            ['Chó', 'Boerboel'],
            ['Chó', 'Bolognese'],
            ['Chó', 'Collie Biên Giới (Border Collie)'],
            ['Chó', 'Border Terrier'],
            ['Chó', 'Borzoi'],
            ['Chó', 'Boston Terrier'],
            ['Chó', 'Bouvier des Ardennes'],
            ['Chó', 'Bouvier des Flandres'],
            ['Chó', 'Võ Sĩ (Boxer)'],
            ['Chó', 'Boykin Spaniel'],
            ['Chó', 'Bracco Italiano'],
            ['Chó', 'Braque d\'Auvergne'],
            ['Chó', 'Braque du Bourbonnais'],
            ['Chó', 'Braque Francais'],
            ['Chó', 'Brazilian Terrier'],
            ['Chó', 'Briard'],
            ['Chó', 'Briquet Griffon Vendeen'],
            ['Chó', 'Brittany Spaniel'],
            ['Chó', 'Broholmer'],
            ['Chó', 'Brussels Griffon'],
            ['Chó', 'Bulldog (English)'],
            ['Chó', 'Bull Mastiff'],
            ['Chó', 'Bull Terrier'],
            ['Chó', 'BullBoxer'],
            ['Chó', 'Ca de Bou'],
            ['Chó', 'Cairn Terrier'],
            ['Chó', 'Canaan Dog'],
            ['Chó', 'Canadian Eskimo Dog'],
            ['Chó', 'Canarian Warren Hound'],
            ['Chó', 'Cane Corso'],
            ['Chó', 'Cardigan Welsh Corgi'],
            ['Chó', 'Carolina Dog'],
            ['Chó', 'Catahoula Leopard Dog'],
            ['Chó', 'Cavalier King Charles Spaniel'],
            ['Chó', 'Central Asian Shepherd Dog'],
            ['Chó', 'Cesky Fousek'],
            ['Chó', 'Cesky Terrier'],
            ['Chó', 'Chesapeake Bay Retriever'],
            ['Chó', 'Chihuahua'],
            ['Chó', 'Chinese Crested Dog'],
            ['Chó', 'Chinese Shar-Pei'],
            ['Chó', 'Chinook'],
            ['Chó', 'Tông Sư Khuyển/Sư Tử Xù/Chó Gấu (Chow Chow)'],
            ['Chó', 'Cirneco dell Etna'],
            ['Chó', 'Clumber Spaniel'],
            ['Chó', 'Cockerpoo Toy'],
            ['Chó', 'Cockerpoo Miniature'],
            ['Chó', 'Cockerpoo Standard'],
            ['Chó', 'Tây Ban Nha (Cocker Spaniel)'],
            ['Chó', 'Collie'],
            ['Chó', 'Collie Smooth'],
            ['Chó', 'Coonhound'],
            ['Chó', 'Coton de Tulear'],
            ['Chó', 'Croatian Shepherd Dog'],
            ['Chó', 'Curly-coated Retriever'],
            ['Chó', 'Czechoslovakian Wolfdog'],
            ['Chó', 'Lạp Xưởng/Xúc xích cỡ bé (Dachshund Miniature)'],
            ['Chó', 'Lạp Xưởng/Xúc xích tiêu chuẩn (Dachshund Standard)'],
            ['Chó', 'Đốm (Dalmatian)'],
            ['Chó', 'Dandie Dinmont Terrier'],
            ['Chó', 'Danish-Swedish Farmdog'],
            ['Chó', 'Deutscher Wachtelhund'],
            ['Chó', 'Dobermann Pinscher'],
            ['Chó', 'Dogo Argentino'],
            ['Chó', 'Dogue de Bordeaux'],
            ['Chó', 'Drentsche Patrijshond'],
            ['Chó', 'Drever'],
            ['Chó', 'Dunker'],
            ['Chó', 'Dutch Shepherd'],
            ['Chó', 'Dutch Smoushond'],
            ['Chó', 'English Setter'],
            ['Chó', 'English Toy Terrier'],
            ['Chó', 'Entlebucher Mountain Dog'],
            ['Chó', 'Eskimo Dog Miniature'],
            ['Chó', 'Eskimo Dog Toy'],
            ['Chó', 'Eskimo Dog Standard'],
            ['Chó', 'Estrela Mountain Dog'],
            ['Chó', 'Eurasier'],
            ['Chó', 'Field Spaniel'],
            ['Chó', 'Fila Brasileiro'],
            ['Chó', 'Finnish Hound'],
            ['Chó', 'Finnish Lapphund'],
            ['Chó', 'Finnish Spitz'],
            ['Chó', 'Flat-coated Retriver'],
            ['Chó', 'Foxhound'],
            ['Chó', 'Fox Terrier'],
            ['Chó', 'French Bulldog'],
            ['Chó', 'Germany Shorthaired Pointer'],
            ['Chó', 'Germany Pinscher'],
            ['Chó', 'Becgie Đức (German Shepherd Dog - GSD)'],
            ['Chó', 'German Spaniel'],
            ['Chó', 'German Spitz Klein'],
            ['Chó', 'German Spitz Mittel'],
            ['Chó', 'German Spitz Gross'],
            ['Chó', 'Giant Schnauzer'],
            ['Chó', 'Glen of Immal Terrier'],
            ['Chó', 'Golden (Golden Retriever)'],
            ['Chó', 'Goldendoodle'],
            ['Chó', 'Gordon Setter'],
            ['Chó', 'Grand Basset Griffon Vendeen'],
            ['Chó', 'Grand Bleu de Gascogne'],
            ['Chó', 'Great Dane'],
            ['Chó', 'Great Pyrenees'],
            ['Chó', 'Greater Swiss Mountain Dog'],
            ['Chó', 'Greenland Dog'],
            ['Chó', 'Greyhound'],
            ['Chó', 'Griffon Bruxellois'],
            ['Chó', 'Hamiltonstovare'],
            ['Chó', 'Harrier'],
            ['Chó', 'Havanese'],
            ['Chó', 'Hokkaido'],
            ['Chó', 'Hovawart'],
            ['Chó', 'Hungarian Puli'],
            ['Chó', 'Hungarian Vizsla'],
            ['Chó', 'Ibizan Hound'],
            ['Chó', 'Icelandic Sheepdog'],
            ['Chó', 'Irish Red and White Setter'],
            ['Chó', 'Irish Setter'],
            ['Chó', 'Irish Terrier'],
            ['Chó', 'Irish Water Spaniel'],
            ['Chó', 'Irish Wolfhound'],
            ['Chó', 'Italian Greyhound'],
            ['Chó', 'Jack Russell Terrier'],
            ['Chó', 'Japanese Akita'],
            ['Chó', 'Nhật Xù (Japanese Chin)'],
            ['Chó', 'Japanese Spitz'],
            ['Chó', 'Japanese Terrier'],
            ['Chó', 'Jindo'],
            ['Chó', 'Kai'],
            ['Chó', 'Karelian Bear Dog'],
            ['Chó', 'Karst Shepherd Dog'],
            ['Chó', 'Keeshond'],
            ['Chó', 'Kerry Blue Terrier'],
            ['Chó', 'King Charles Spaniel (English Toy Spaniel)'],
            ['Chó', 'King Shepherd'],
            ['Chó', 'Kishu'],
            ['Chó', 'Komondor'],
            ['Chó', 'Kooikerhondje'],
            ['Chó', 'Kromfohrlander'],
            ['Chó', 'Kuvasz'],
            ['Chó', 'Labradoodle Miniature'],
            ['Chó', 'Labradoodle Medium'],
            ['Chó', 'Labradoodle Standard'],
            ['Chó', 'Lab (Labrador Retriever)'],
            ['Chó', 'Lagotto Romagnolo'],
            ['Chó', 'Laekenois'],
            ['Chó', 'Lakeland Terrier'],
            ['Chó', 'Lancashire Heeler'],
            ['Chó', 'Lapponian Herder'],
            ['Chó', 'Large Munsterlander'],
            ['Chó', 'Sư tử Đức (Leonberger)'],
            ['Chó', 'Lhasa Apso'],
            ['Chó', 'Lowchen'],
            ['Chó', 'Lurcher'],
            ['Chó', 'Maltese'],
            ['Chó', 'Manchester Terrier'],
            ['Chó', 'Maremma Sheepdog'],
            ['Chó', 'Mastiff'],
            ['Chó', 'Mexican Hairless Miniature'],
            ['Chó', 'Mexican Hairless Intermediate'],
            ['Chó', 'Mexican Hairless Standard'],
            ['Chó', 'Mountain Cur'],
            ['Chó', 'Mudi'],
            ['Chó', 'Neapolitan Mastiff'],
            ['Chó', 'New Guinea Singing Dog'],
            ['Chó', 'New Zealand Huntaway'],
            ['Chó', 'Newfoundland'],
            ['Chó', 'Norfolk Terrier'],
            ['Chó', 'Norrbottenspets'],
            ['Chó', 'Norwegian Buhund'],
            ['Chó', 'Norwegian Elkhound'],
            ['Chó', 'Norwegian Lundehund'],
            ['Chó', 'Norwich Terrier'],
            ['Chó', 'Nova Scotia Duck Tolling Retriever'],
            ['Chó', 'Old English Sheepdog'],
            ['Chó', 'Otterhound'],
            ['Chó', 'Papillon'],
            ['Chó', 'Parson Russell Terrier'],
            ['Chó', 'Bắc Kinh (Pekingese)'],
            ['Chó', 'Pembroke Welsh Corgi'],
            ['Chó', 'Peruvian Inca Orchid'],
            ['Chó', 'Peruvian Hairless Miniature'],
            ['Chó', 'Peruvian Hairless Medio'],
            ['Chó', 'Peruvian Hairless Grande'],
            ['Chó', 'Petit Basset Griffon Vendeen'],
            ['Chó', 'Pharaoh Hound'],
            ['Chó', 'Picardy Sheepdog'],
            ['Chó', 'Plott'],
            ['Chó', 'Pointers'],
            ['Chó', 'Polish Lowland Sheepdog'],
            ['Chó', 'Fox/Phốc sóc/Pom Pom (Pomeranian)'],
            ['Chó', 'poodle Toy'],
            ['Chó', 'poodle Miniature'],
            ['Chó', 'poodle Medium'],
            ['Chó', 'Porcelaine'],
            ['Chó', 'Portugese Podengo Pequeno'],
            ['Chó', 'Portugese Podengo Medio'],
            ['Chó', 'Portugese Podengo Grande'],
            ['Chó', 'Portugese Pointing Dog'],
            ['Chó', 'Portugese Sheepdog'],
            ['Chó', 'Portugese Water Dog'],
            ['Chó', 'Portugese WatchDog'],
            ['Chó', 'Pudelpointer'],
            ['Chó', 'Pug'],
            ['Chó', 'Puli'],
            ['Chó', 'Pumi'],
            ['Chó', 'Pyrenean Mastiff'],
            ['Chó', 'Pyrenean Shepherd'],
            ['Chó', 'Pyrenean Mountain Dog'],
            ['Chó', 'Rafeiro do Alentejo'],
            ['Chó', 'Rat Terrier Miniature'],
            ['Chó', 'Rat Terrier Standard'],
            ['Chó', 'Redbone Coonhound'],
            ['Chó', 'Rhodesian Ridgeback'],
            ['Chó', 'Rottweiler'],
            ['Chó', 'Russian Black Terrier'],
            ['Chó', 'Russian Toy'],
            ['Chó', 'St Bernard'],
            ['Chó', 'Saarloos Wolfdog'],
            ['Chó', 'Saluki'],
            ['Chó', 'Samoyed'],
            ['Chó', 'Sarplaninac'],
            ['Chó', 'Schipperke'],
            ['Chó', 'Schnauzer'],
            ['Chó', 'Scottish Deerhound'],
            ['Chó', 'Scottish Terrier'],
            ['Chó', 'Sealyham Terrier'],
            ['Chó', 'Segugio Italiano'],
            ['Chó', 'Shar Pei'],
            ['Chó', 'Shetland Sheepdog'],
            ['Chó', 'Shiba Inu'],
            ['Chó', 'Thạch sư Khuyển/Sư Tử Đá (Shih Tzu)'],
            ['Chó', 'Shikoku'],
            ['Chó', 'tuyết kéo xe (Siberian Husky)'],
            ['Chó', 'Silky Terrier'],
            ['Chó', 'Skye Terrier'],
            ['Chó', 'Sloughi'],
            ['Chó', 'Slovensky Cuvac'],
            ['Chó', 'Small Munsterlander'],
            ['Chó', 'Soft-coated Wheaten Terrier'],
            ['Chó', 'Spanish Water Dog'],
            ['Chó', 'Spinone Italiano'],
            ['Chó', 'Spitz'],
            ['Chó', 'Stabyhoun'],
            ['Chó', 'Staffordshire Bull Terrier'],
            ['Chó', 'Sussex Spaniel'],
            ['Chó', 'Swedish Lapphund'],
            ['Chó', 'Swedish Lapland'],
            ['Chó', 'Swedish Vallhund'],
            ['Chó', 'Thai Ridgeback'],
            ['Chó', 'Ngao Tây Tạng (Tibetan Mastiff)'],
            ['Chó', 'Tibetan Spaniel'],
            ['Chó', 'Tibetan Terrier'],
            ['Chó', 'Tosa'],
            ['Chó', 'Treeing Walker Coonhound'],
            ['Chó', 'Vizsla'],
            ['Chó', 'Volpino Italiano'],
            ['Chó', 'Xoloitzcuintli Miniature'],
            ['Chó', 'Xoloitzcuintli Intermediate'],
            ['Chó', 'Xoloitzcuintli Standard'],
            ['Chó', 'Weimaraner'],
            ['Chó', 'Welsh Terrier'],
            ['Chó', 'West Highland White Terrier'],
            ['Chó', 'Whippet'],
            ['Chó', 'Wirehaired Pointing Griffon'],
            ['Chó', 'Yorkshire Terrier'],
            ['Chó', 'Bắc Hà'],
            ['Chó', 'lào'],
            ['Chó', 'sói Rừng'],
            ['Chó', 'vàng'],
            ['Chó', 'H\' Mông'],
            ['Chó', 'Laika'],
            ['Chó', 'Phú Quốc'],
            ['Chó', 'sharku'],
            ['Chó', 'lai kích thước lớn (>28 kg)'],
            ['Chó', 'lai kích thước trung bình (11-28kg)'],
            ['Chó', 'lai kích thước nhỏ (<11 kg)'],
            ['Chó', 'khác'],
            ['Mèo', 'Abyssinian'],
            ['Mèo', 'American Bobtail'],
            ['Mèo', 'Mỹ tai xoắn (American Curl)'],
            ['Mèo', 'Mỹ lông ngắn (American Short Hair)'],
            ['Mèo', 'American Wirehair'],
            ['Mèo', 'Balinese'],
            ['Mèo', 'rừng (Bengal)'],
            ['Mèo', 'Birman'],
            ['Mèo', 'Bombay'],
            ['Mèo', 'Anh lông ngắn (British Short Hair)'],
            ['Mèo', 'Anh lông dài (British Long Hair)'],
            ['Mèo', 'Burmese'],
            ['Mèo', 'Burmilla'],
            ['Mèo', 'Chartreux'],
            ['Mèo', 'Chausie'],
            ['Mèo', 'Chinese Li Hua'],
            ['Mèo', 'Colorpoint Shorthair'],
            ['Mèo', 'Cornish Rex'],
            ['Mèo', 'Devon Rex'],
            ['Mèo', 'Egyptian Mau'],
            ['Mèo', 'European Burmese'],
            ['Mèo', 'Ba Tư lông ngắn (Exotic Shorthair)'],
            ['Mèo', 'Havana Brown'],
            ['Mèo', 'Himalayan'],
            ['Mèo', 'Japanese Bobtail'],
            ['Mèo', 'Korat'],
            ['Mèo', 'LaPerm'],
            ['Mèo', 'Mỹ lông dài (Maine Coon)'],
            ['Mèo', 'cộc đuôi (Manx)'],
            ['Mèo', 'Munchkin'],
            ['Mèo', 'Norwegian Forest'],
            ['Mèo', 'Ocicat'],
            ['Mèo', 'Oriental'],
            ['Mèo', 'Ba Tư lông dài (Persian)'],
            ['Mèo', 'RagaMuffin'],
            ['Mèo', 'Ragdoll'],
            ['Mèo', 'Nga mắt xanh (Russian Blue)'],
            ['Mèo', 'Savannah Cat'],
            ['Mèo', 'tai cụp Scotland (Scottish Fold)'],
            ['Mèo', 'Selkirk Rex'],
            ['Mèo', 'Xiêm (Siamese)'],
            ['Mèo', 'Siberian'],
            ['Mèo', 'Singapura'],
            ['Mèo', 'Snowshoe'],
            ['Mèo', 'Somali'],
            ['Mèo', 'nhân sư không lông (Sphynx)'],
            ['Mèo', 'Tonkinese'],
            ['Mèo', 'Thổ Nhĩ Kỳ (Turkish Angora)'],
            ['Mèo', 'Van Thổ (Turkish Van)'],
            ['Mèo', 'mướp'],
            ['Mèo', 'mun'],
            ['Mèo', 'tam thể'],
            ['Mèo', 'vàng'],
            ['Mèo', 'nhị thể'],
            ['Mèo', 'Mixed Breed'],
            ['Thỏ', 'khác'],
            ['Chuột', 'khác'],
            ['Nhím', 'khác'],
            ['Bò sát', 'khác'],
            ['Chim', 'khác'],
            ['Gà', 'khác'],
            ['Cá', 'khác'],
            ['Dê', 'khác'],
            ['Khỉ', 'khác'],
            ['Rùa', 'khác'],
            ['Chồn Xương', 'khác'],
            ['Heo', 'khác'],
            ['Sóc', 'khác'],
            ['Chồn', 'Khác'],
            ['Beo trắng', 'Khác'],
            ['Ngỗng', 'Khác'],
            ['Mèo', 'khác'],
        ];

        foreach ($animals as $key => $animal) {
            Animal::create([
                'specie' => $animal[0],
                'lineage' => $animal[1],
            ]);
        }
    }
}
