<?php

namespace Database\Seeders;

use App\Models\Disease;
use App\Models\Dosage;
use App\Models\Medicine;
use App\Models\Symptom;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $symptoms = [
            [1, 'Môi trường sống', 'Thông tin chung'],
            [2, 'Thức ăn gần đây', 'Thông tin chung'],
            [3, 'Cân nặng', 'Thông tin chung'],
            [4, 'Nhiệt độ', 'Thông tin chung'],
            [5, 'Tiêu chảy', 'Tiêu hóa'],
            [6, 'Táo bón', 'Tiêu hóa'],
            [7, 'Nổi mẩn đỏ', 'Da'],
            [8, 'Ngứa', 'Lông da'],
            [9, 'Đi ngoài nhiều', 'Tiêu hóa'],
            [10, 'Khó thở', 'Hô hấp'],
            [11, 'Nhịp tim nhanh', 'Tim mạch'],
            [12, 'Ho khan', 'Hô hấp'],
            [13, 'Dịch mũi xanh', 'Hô hấp'],
            [14, 'Sốt', 'Thể trạng chung'],
            [15, 'Không tiểu', 'Tiết niệu'],
            [16, 'Chảy máu mũi', 'Hô hấp'],
            [21, 'Bỏ ăn', 'Chế độ chăm sóc'],
            [25, 'Thức ăn hàng ngày', 'Chế độ chăm sóc'],
            [26, 'Thức ăn trong 5 ngày gần nhất', 'Chế độ chăm sóc'],
            [27, 'Uống nước', 'Chế độ chăm sóc'],
            [28, 'Tầm vóc (BCS)', 'Thể trạng chung'],
            [29, 'Niêm mạc', 'Thể trạng chung'],
            [30, 'Thời gian lắp đầy mao mạch', 'Thể trạng chung'],
            [31, 'Nhiệt độ', 'Thể trạng chung'],
            [32, 'Độ mất nước', 'Thể trạng chung'],
            [33, 'Đi đứng khập khiểng', 'Thể trạng chung'],
            [34, 'Đau khi sờ nắn (vị trí)', 'Thể trạng chung'],
            [35, 'Huyết áp', 'Thể trạng chung'],
            [36, 'Ve, rận, bọ chét', 'Lông da'],
            [37, 'Rụng lông dối xứng', 'Lông da'],
            [38, 'Ngứa (vị trí)', 'Lông da'],
            [39, 'Ngứa toàn thân', 'Lông da'],
            [40, 'Phản xạ liếm 2 chân or 4 chân', 'Lông da'],
            [41, 'Phản xạ liếm vùng hậu môn', 'Lông da'],
            [42, 'Độ ẩm or nhầy or nhớt của da', 'Lông da'],
            [43, 'xuất huyết dưới da', 'Lông da'],
            [44, 'Nốt mủ/mảng mủ', 'Lông da'],
            [45, 'Nốt đỏ (không phải xuất huyết)', 'Lông da'],
            [46, 'Nốt sần/U sần', 'Lông da'],
            [47, 'Màu sắc da', 'Lông da'],
            [48, 'Gan bàn chân', 'Lông da'],
            [49, 'Gương mũi', 'Lông da'],
            [50, 'Gãy chân (vị trí)', 'Cơ xương'],
            [51, 'Abscesss (vị trí)', 'Cơ xương'],
            [52, 'Nhịp tim (BPM)', 'Tim mạch'],
            [53, 'Tiếng tim', 'Tim mạch'],
            [54, 'Nhịp mạch', 'Chọn nhóm cơ quan'],
            [55, 'Dịch mũi', 'Hô hấp'],
            [56, 'chảy máu mũi', 'Hô hấp'],
            [57, 'Ho khạc', 'Hô hấp'],
            [58, 'Ho khan', 'Hô hấp'],
            [59, 'Ho có đàm', 'Hô hấp'],
            [60, 'Ho ra máu', 'Hô hấp'],
            [61, 'Ho ban ngày', 'Hô hấp'],
            [62, 'Ho ban đêm', 'Hô hấp'],
            [63, 'Amidal', 'Hô hấp'],
            [64, 'Nhịp hô hấp', 'Hô hấp'],
            [65, 'Âm phổi', 'Hô hấp'],
            [66, 'Răng', 'Tiêu hóa'],
            [67, 'Mất răng', 'Tiêu hóa'],
            [68, 'Nha chu', 'Tiêu hóa'],
            [69, 'Nướu', 'Tiêu hóa'],
            [70, 'Miệng', 'Tiêu hóa'],
            [71, 'Hầu họng', 'Tiêu hóa'],
            [72, 'Lưỡi', 'Tiêu hóa'],
            [73, 'Thực quản', 'Tiêu hóa'],
            [74, 'Số lần nôn ói', 'Tiêu hóa'],
            [75, 'Sản phẩm trong dịch ói', 'Tiêu hóa'],
            [76, 'Phân sệt/màu sắc/số lần đi phân/sản phẩm trong phân', 'Tiêu hóa'],
            [77, 'Phân lỏng/màu sắc/số lần đi phân/sản phẩm trong phân', 'Tiêu hóa'],
            [78, 'Có tiểu được không?', 'Tiết niệu'],
            [79, 'Tiểu gắt/tiểu ra máu/tiểu bậy', 'Tiết niệu'],
            [80, 'Màu nước tiểu', 'Tiết niệu'],
            [81, 'Mùi', 'Tiết niệu'],
            [82, 'Số lần đi tiểu', 'Tiết niệu'],
            [83, 'Tinh hoàn', 'Sinh dục'],
            [84, 'Dương vật', 'Sinh dục'],
            [85, 'Phối giống', 'Sinh dục'],
            [86, 'Ngừa thai?', 'Sinh dục'],
            [87, 'Số lứa đẻ', 'Sinh dục'],
            [88, 'Xảy thai', 'Sinh dục'],
            [89, 'Tuyến/bầu vú', 'Sinh dục'],
            [90, 'Âm đạo', 'Sinh dục'],
            [91, 'Dịch tai', 'Tai'],
            [92, 'Dày da tai', 'Tai'],
            [93, 'Đổi màu da tai', 'Tai'],
            [94, 'Ngứa tai/lắc tai', 'Tai'],
            [95, 'Thính giác: bình thường hay bất thường', 'Tai'],
            [96, 'Dị tật mắt', 'Mắt'],
            [97, 'Kết mạc', 'Mắt'],
            [98, 'Gíac mạc', 'Mắt'],
            [99, 'Tăng nhãn áp', 'Mắt'],
            [100, 'Đục thủy tinh thể', 'Mắt'],
            [101, 'Thị lực bình thường hay bất thường', 'Mắt'],
            [102, 'Chảy nước mắt', 'Mắt'],
            [103, 'Quặn mi', 'Mắt'],
            [104, 'Cherry mắt', 'Mắt'],
            [105, 'Kêu la', 'Thần kinh'],
            [106, 'Liệt 1 phần', 'Thần kinh'],
            [107, 'Liệt toàn thân', 'Thần kinh'],
            [108, 'Thiếu điều vận động', 'Thần kinh'],
            [109, 'Hôn mê', 'Thần kinh'],
            [110, 'Co giật', 'Thần kinh'],
            [111, 'Tiểu bậy', 'Tiết niệu'],
            [112, 'Phân khô/táo bón', 'Tiêu hóa'],
            [113, 'màu sắc phân', 'Tiêu hóa'],
            [114, 'dạ dày', 'Tiêu hóa'],
        ];

        foreach ($symptoms as $key => $symptom) {
            Symptom::create([
                'company_id' => 1,
                'id' => $symptom[0],
                'name' => $symptom[1],
                'group' => $symptom[2],
            ]);
        }

        $diseases = [
            [9, 'Viêm da do nấm Malassizia', NULL, 'Môi trường ẩm ướt, thiếu ánh nắng', 'Thay đổi màu sắc da, rụng lông, bệnh tái đi tái lại', 'Vệ sinh môi trường sạch sẽ, tắm định kỳ, tránh tiếp xúc.'],
            [10, 'Viêm da do nấm Mirosporium', 'chưa rõ', 'Tiếp xúc, môi trường ẩm ướt....', 'tổn thương da cục bộ or toàn thân, lông xơ, sa có vảy', 'tắm, dọn dẹp môi trường định kỳ'],
            [11, 'Tiêu chảy máu do Parvovirus', '5-7 ngày', 'chất thải', 'tiêu chảy mãn tính', 'tiêm phòng định kỳ'],
            [12, 'Bệnh Hô Viêm Đường Hô Hấp Do Vius Care', '5-7', NULL, NULL, NULL],
            [13, 'Viêm da do ký sinh trùng Demodex', NULL, NULL, NULL, NULL],
            [14, 'Viêm da do ký sinh trùng Sacroptes', NULL, NULL, NULL, NULL],
            [15, 'Viêm da có mủ', NULL, NULL, NULL, NULL],
            [16, 'Viêm da do nội tiết tố', NULL, NULL, NULL, NULL],
            [17, 'Viêm da do dị ứng', NULL, NULL, NULL, NULL],
            [18, 'Rối loạn tiêu hóa do ăn uống', NULL, NULL, NULL, NULL],
            [19, 'Bệnh đường ruột do Giun Đũa', NULL, NULL, NULL, NULL],
            [20, 'Bệnh đường ruột do Giun Móc', NULL, NULL, NULL, NULL],
            [21, 'Bệnh đường ruột do Cầu Trùng', NULL, NULL, NULL, NULL],
            [22, 'Nhiễm khuẩn đường tiêu hóa', NULL, NULL, NULL, NULL],
            [23, 'Viêm dạ dày ruột cấp tính', NULL, NULL, NULL, NULL],
            [24, 'Viêm dạ dày ruột mãn tính', NULL, NULL, NULL, NULL],
            [25, 'Tiêu chảy do virus FPV', NULL, NULL, NULL, NULL],
            [26, 'viêm hô hấp do nhiễm khuẩn', NULL, NULL, NULL, NULL],
            [27, 'Viêm hô hấp do Nấm', NULL, NULL, NULL, NULL],
            [28, 'Viêm hô hấp do dị ứng', NULL, NULL, NULL, NULL],
            [29, 'Bí tiểu do tắc nghẽn', NULL, NULL, NULL, NULL],
            [30, 'Viêm đường niệu do vi khuẩn', NULL, NULL, NULL, NULL],
            [31, 'Ngộ độc tiêu hóa do ăn uống', NULL, NULL, NULL, NULL],
            [32, 'Viêm tử cung', NULL, NULL, NULL, NULL],
            [33, 'Viêm tắc tuyến vú', NULL, NULL, NULL, NULL],
            [34, 'Khối u ở tuyến vú', NULL, NULL, NULL, NULL],
            [35, 'Gãy xương', NULL, NULL, NULL, NULL],
            [36, 'Viêm tai do ký sinh trùng', NULL, NULL, NULL, NULL],
            [37, 'Viêm tai do vi khuẩn', NULL, NULL, NULL, NULL],
            [38, 'Viêm tai do nấm', NULL, NULL, NULL, NULL],
            [39, 'Viêm tai do nội tiết tố', NULL, NULL, NULL, NULL],
            [40, 'Viêm tai do dị ứng', NULL, NULL, NULL, NULL],
            [41, 'Viêm kết mạc', NULL, NULL, NULL, NULL],
            [42, 'Viêm giác mạc', NULL, NULL, NULL, NULL],
            [43, 'Loét giác mạc', NULL, NULL, NULL, NULL],
            [44, 'Bệnh tiểu đường', NULL, NULL, NULL, NULL],
            [45, 'Bệnh ký sinh trùng đường máu', NULL, NULL, NULL, NULL],
            [46, 'Viêm tụy', NULL, NULL, NULL, NULL],
            [47, 'Dị vật thực quản', NULL, NULL, NULL, NULL],
            [48, 'Dị vật dạ dày-ruột', NULL, NULL, NULL, NULL],
            [49, 'Tắt ruột/lồng ruột', NULL, NULL, NULL, NULL],
            [50, 'Tắt ruột/lồng ruột', NULL, NULL, NULL, NULL],
            [51, 'Rối loạn tiền đình', NULL, NULL, NULL, NULL],
            [52, 'Viêm túi hôi', NULL, NULL, NULL, NULL],
            [53, 'Viêm miệng', NULL, NULL, NULL, NULL],
            [54, 'Bệnh thận', NULL, NULL, NULL, NULL],
            [55, 'Bệnh viêm gan', NULL, NULL, NULL, NULL],
            [56, 'Thoát vị đáy chậu', NULL, NULL, NULL, NULL],
            [57, 'Viêm bàng quang', NULL, NULL, NULL, NULL],
            [58, 'Giun Tim ký sinh ở hệ máu', NULL, NULL, NULL, NULL],
        ];

        foreach ($diseases as $key => $disease) {
            Disease::create([
                'company_id' => 1,
                'id' => $disease[0],
                'name' => $disease[1],
                'incubation' => $disease[2],
                'communicability' => $disease[3],
                'complication' => $disease[4],
                'prevention' => $disease[5],
            ]);
        }

        $medicines = [
            [1, 'Ketoconazol', 644, 'ketocanazol 200mg20mg/kg', 'chống liếm', NULL, NULL, NULL],
            [2, 'Enrofloxacine 50mg', 577, 'enrofloxacine 5%', 'chó dưới 6 tháng tuổi và chó già', 'Mỹ', NULL, NULL],
            [3, 'azithromycin 500mg', 929, NULL, NULL, NULL, NULL, '2024-09-07 10:55:11'],
            [4, 'sfcXZCdfvsfvcsacxvcbcs', 1333, NULL, NULL, NULL, NULL, '2024-09-07 10:55:06'],
            [5, 'Kali', 1294, 'Kali 600mg', NULL, NULL, NULL, '2024-09-19 15:31:17'],
            [6, 'Ivermectin', 1334, NULL, NULL, NULL, NULL, '2024-09-19 15:31:28'],
            [7, 'Dexamethasole 152mg', 1338, NULL, NULL, NULL, NULL, NULL],
            [8, 'Sucralfat', 676, NULL, NULL, NULL, NULL, NULL],
            [9, 'Prednisolone 4mg', 638, NULL, NULL, NULL, NULL, NULL],
            [10, 'Praziquantel', 1295, NULL, NULL, NULL, NULL, NULL],
            [11, 'meloxicam', 1280, NULL, NULL, NULL, NULL, NULL],
            [12, 'Ketoprofen 50mg', 593, NULL, NULL, NULL, NULL, NULL],
            [13, 'Alpha chymotrysin 4mg', 589, NULL, NULL, NULL, NULL, NULL],
            [14, 'Hematofos B12', 599, NULL, NULL, NULL, NULL, NULL],
            [15, 'Catosal', 601, NULL, NULL, NULL, NULL, NULL],
            [16, 'Aminioplex', 600, NULL, NULL, NULL, NULL, NULL],
            [17, 'Atropin 50mg', 613, NULL, NULL, NULL, NULL, NULL],
            [18, 'Chlopheniramine 10mg', 597, NULL, NULL, NULL, NULL, NULL],
            [19, 'Tolfen', 717, NULL, NULL, NULL, NULL, NULL],
            [20, 'Meloxicam 50mg', 596, NULL, NULL, NULL, NULL, NULL],
            [21, 'Oxytocine', 612, NULL, NULL, NULL, NULL, NULL],
            [22, 'Shotapen', 579, 'Pennici', NULL, NULL, NULL, NULL],
            [23, 'Doxyciline', 587, NULL, NULL, NULL, NULL, NULL],
            [24, 'Vitamin khoáng', 615, NULL, NULL, NULL, NULL, NULL],
            [25, 'Omega 3&6-vitamine', 617, NULL, NULL, NULL, NULL, NULL],
            [26, 'Renal', 611, NULL, NULL, NULL, NULL, NULL],
            [27, 'Hepadol', 606, NULL, NULL, NULL, NULL, NULL],
            [28, 'Struvite mèo', 609, NULL, NULL, NULL, NULL, NULL],
            [29, 'Itraconazole', 716, NULL, NULL, NULL, NULL, NULL],
            [30, 'Carbon hình cầu', 1025, NULL, NULL, NULL, NULL, NULL],
            [31, 'Glusamine', 1281, NULL, NULL, NULL, NULL, NULL],
            [32, 'Heparenal', 607, NULL, NULL, NULL, NULL, NULL],
            [33, 'Bổ máu', 571, NULL, NULL, NULL, NULL, NULL],
            [34, 'Tulathromycine 50mg', 580, NULL, NULL, NULL, NULL, NULL],
            [35, 'Skincoat', 602, NULL, NULL, NULL, NULL, NULL],
            [36, 'Bổ thận', 603, NULL, NULL, NULL, NULL, NULL],
            [37, 'Bổ gan', 570, NULL, NULL, NULL, NULL, NULL],
            [38, 'Calci', 604, NULL, NULL, NULL, NULL, NULL],
            [39, 'Tiết niệu mèo', 610, NULL, NULL, NULL, NULL, NULL],
            [40, 'Prednisolone 5mg', 594, NULL, NULL, NULL, NULL, NULL],
            [41, 'Chlopheniramine 4mg', 641, NULL, NULL, NULL, NULL, NULL],
            [42, 'Carbon hoạt tính', 1021, NULL, NULL, NULL, NULL, NULL],
            [43, 'Amox+clavulanic 250mg', 567, NULL, NULL, NULL, NULL, NULL],
            [44, 'Clindamycine 150mg', 585, NULL, NULL, NULL, NULL, NULL],
            [45, 'Enrofloxacine 50mg', 568, NULL, NULL, NULL, NULL, NULL],
            [46, 'Marbofloxacine 20mg', 588, NULL, NULL, NULL, NULL, NULL],
            [47, 'Amox+clavulanic 50mg', 565, NULL, NULL, NULL, NULL, NULL],
        ];

        foreach ($medicines as $key => $medicine) {
            Medicine::create([
                'company_id' => 1,
                'id' => $medicine[0],
                'name' => $medicine[1],
                'variable_id' => $medicine[2],
                'prognosis' => $medicine[3],
                'contraindications' => $medicine[4],
                'advice' => $medicine[5],
                'sample_dosages' => $medicine[6],
                'deleted_at' => $medicine[7],
            ]);
        }

        $dosages = [
            [1, 1, '0.05', '1', 'Đường uống (PO)', 7, 'Chó', 6, 1],
            [2, 5, '1', '1', 'Đường uống (PO)', 1, 'Mèo', 1, 1],
            [3, 6, '1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 6, 20],
            [4, 8, '0.2', '2', 'Đường uống (PO)', 3, 'Chó', 1, NULL],
            [5, 7, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [6, 2, '0.1', '1', 'Tiêm dưới da (SC)', 3, 'Chó', 6, NULL],
            [7, 1, '0.05', '1', 'PO', 7, 'Mèo', 6, NULL],
            [8, 2, '0.1', '1', 'Tiêm dưới da (SC)', 3, 'Mèo', 6, NULL],
            [9, 7, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [10, 8, '0.2', '2', 'Đường uống (PO)', 3, 'Chó', 1, NULL],
            [11, 9, '0.25', '2', 'Đường uống (PO)', 5, 'Chó', 3, NULL],
            [12, 12, '0.06', '1', 'Tiêm dưới da (SC)', 3, 'Chó', 3, NULL],
            [13, 12, '0.06', '1', 'Tiêm dưới da (SC)', 3, 'Mèo', 3, NULL],
            [14, 11, '0.2', '1', 'Đường uống (PO)', 3, 'Chó', 3, NULL],
            [15, 11, '0.1', '1', 'Đường uống (PO)', 3, 'Mèo', 3, NULL],
            [16, 13, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [17, 14, '0.1', '1', 'Tiêm tĩnh mạch (IV)', 1, 'Chó', 3, NULL],
            [18, 14, '0.2', '1', 'Tiêm tĩnh mạch (IV)', 1, 'Chó', 3, NULL],
            [19, 15, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [20, 15, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [21, 17, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [22, 18, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [23, 18, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [24, 19, '0.025', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [25, 19, '0.03', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [26, 20, '0.04', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [27, 20, '0.06', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [28, 21, '0.125', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [29, 21, '0.125', '1', 'Tiêm dưới da (SC)', 1, 'Mèo', 3, NULL],
            [30, 22, '0.1', '1', 'Tiêm dưới da (SC)', 1, 'Chó', 3, NULL],
            [31, 24, '0.2', '1', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [32, 25, '0.2', '1', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [33, 25, '0.2', '1', 'Đường uống (PO)', 1, 'Mèo', 3, NULL],
            [34, 26, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [35, 27, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [36, 28, '0.5', '1', 'Đường uống (PO)', 1, 'Mèo', 6, NULL],
            [37, 29, '0.2', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [38, 29, '0.2', '1', 'Đường uống (PO)', 1, 'Mèo', 6, NULL],
            [39, 30, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [40, 31, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [41, 31, '0.1', '1', 'Đường uống (PO)', 1, 'Mèo', 6, NULL],
            [42, 32, '0.1', '1', 'Đường uống (PO)', 7, 'Chó', 3, NULL],
            [43, 33, '0.25', '1', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [44, 34, '0.1', '1', 'Đường uống (PO)', 1, 'Mèo', 1, NULL],
            [45, 34, '0.2', '1', 'Đường uống (PO)', 1, 'Chó', 1, NULL],
            [46, 35, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [47, 36, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [48, 37, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 6, NULL],
            [49, 38, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 1, NULL],
            [50, 39, '0.2', '1', 'Đường uống (PO)', 1, 'Mèo', 2, NULL],
            [51, 40, '0.2', '2', 'Đường uống (PO)', 3, 'Chó', 3, NULL],
            [52, 41, '0.1', '2', 'Đường uống (PO)', 5, 'Chó', 2, NULL],
            [53, 41, '0.2', '2', 'Đường uống (PO)', 5, 'Mèo', 2, NULL],
            [54, 42, '0.2', '2', 'Đường uống (PO)', 3, 'Chó', 2, NULL],
            [55, 43, '0.06', '2', 'Đường uống (PO)', 5, 'Chó', 6, NULL],
            [56, 44, '0.1', '1', 'Đường uống (PO)', 3, 'Chó', 3, NULL],
            [57, 44, '0.06', '1', 'Đường uống (PO)', 3, 'Chó', 3, NULL],
            [58, 45, '0.1', '1', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [59, 46, '0.1', '2', 'Đường uống (PO)', 1, 'Chó', 3, NULL],
            [60, 47, '0.2', '2', 'Đường uống (PO)', 3, 'Chó', 3, NULL],
        ];

        foreach ($dosages as $key => $dosage) {
            Dosage::create([
                'id' => $dosage[0],
                'medicine_id' => $dosage[1],
                'dosage' => $dosage[2],
                'frequency' => $dosage[3],
                'route' => $dosage[4],
                'quantity' => $dosage[5],
                'specie' => $dosage[6],
                'age' => $dosage[7],
                'weight' => $dosage[8]
            ]);
        }

        DB::statement("
        INSERT INTO `disease_medicine` (`id`, `disease_id`, `medicine_id`) VALUES
        (1, 29, 5),
        (2, 58, 6),
        (7, 12, 2),
        (8, 26, 2),
        (9, 37, 2),
        (10, 57, 2),
        (11, 9, 47),
        (12, 15, 47),
        (13, 22, 47),
        (14, 37, 45);");

        DB::statement("
        INSERT INTO `disease_symptom` (`id`, `disease_id`, `symptom_id`) VALUES
        (4, 11, 21);");
    }
}
