<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Create permissions
        $permissions = [
            ['Read dashboard', 'web', 'Dashboard'],
            ['Read chats', 'web', 'Dashboard'],
            ['Access admin panel', 'web', 'Access admin'],
            ['Access settings page', 'web', 'Access settings'],
            ['Read system logs', 'web', 'Logs'],
            ['Read roles list', 'web', 'Roles'],
            ['Read role details', 'web', 'Roles'],
            ['Create role', 'web', 'Roles'],
            ['Update role', 'web', 'Roles'],
            ['Delete role', 'web', 'Roles'],
            ['Delete multiple roles', 'web', 'Roles'],
            ['Read user list', 'web', 'Users'],
            ['Read user details', 'web', 'Users'],
            ['Create user', 'web', 'Users'],
            ['Update user', 'web', 'Users'],
            ['Change user password', 'web', 'Users'],
            ['Switch user status', 'web', 'Users'],
            ['Delete user', 'web', 'Users'],
            ['Delete multiple users', 'web', 'Users'],
            ['Assign role to user', 'web', 'Users'],
            ['Assign branch to user', 'web', 'Users'],
            ['Assign warehouse to user', 'web', 'Users'],
            ['Read supplier list', 'web', 'Suppliers'],
            ['Read supplier details', 'web', 'Suppliers'],
            ['Create supplier', 'web', 'Suppliers'],
            ['Update supplier', 'web', 'Suppliers'],
            ['Delete supplier', 'web', 'Suppliers'],
            ['Delete multiple suppliers', 'web', 'Suppliers'],
            ['Read branch list', 'web', 'Branches'],
            ['Read branch details', 'web', 'Branches'],
            ['Create branch', 'web', 'Branches'],
            ['Update branch', 'web', 'Branches'],
            ['Delete branch', 'web', 'Branches'],
            ['Delete multiple branches', 'web', 'Branches'],
            ['Read warehouse list', 'web', 'Warehouses'],
            ['Create warehouse', 'web', 'Warehouses'],
            ['Update warehouse', 'web', 'Warehouses'],
            ['Delete warehouse', 'web', 'Warehouses'],
            ['Delete multiple warehouses', 'web', 'Warehouses'],
            ['Read import list', 'web', 'Imports'],
            ['Read import details', 'web', 'Imports'],
            ['Create import', 'web', 'Imports'],
            ['Update import', 'web', 'Imports'],
            ['Delete import', 'web', 'Imports'],
            ['Delete multiple imports', 'web', 'Imports'],
            ['Print import', 'web', 'Imports'],
            ['Export excel import', 'web', 'Imports'],
            ['Read export list', 'web', 'Exports'],
            ['Read export details', 'web', 'Exports'],
            ['Create export', 'web', 'Exports'],
            ['Update export', 'web', 'Exports'],
            ['Delete export', 'web', 'Exports'],
            ['Delete multiple exports', 'web', 'Exports'],
            ['Print export', 'web', 'Exports'],
            ['Export excel export', 'web', 'Exports'],
            ['Read stock list', 'web', 'Stocks'],
            ['Read stock details', 'web', 'Stocks'],
            ['Print stock list', 'web', 'Stocks'],
            ['Export excel stock list', 'web', 'Stocks'],
            ['Read catalogue list', 'web', 'Catalogues'],
            ['Create catalogue', 'web', 'Catalogues'],
            ['Sort catalogue', 'web', 'Catalogues'],
            ['Update catalogue', 'web', 'Catalogues'],
            ['Delete catalogue', 'web', 'Catalogues'],
            ['Delete multiple catalogues', 'web', 'Catalogues'],
            ['Read attribute list', 'web', 'Attributes'],
            ['Create attribute', 'web', 'Attributes'],
            ['Update attribute', 'web', 'Attributes'],
            ['Delete attribute', 'web', 'Attributes'],
            ['Delete multiple attributes', 'web', 'Attributes'],
            ['Read product list', 'web', 'Products'],
            ['Read product details', 'web', 'Products'],
            ['Create product', 'web', 'Products'],
            ['Switch product status', 'web', 'Products'],
            ['Update product', 'web', 'Products'],
            ['Delete product', 'web', 'Products'],
            ['Delete multiple products', 'web', 'Products'],
            ['Export excel product list', 'web', 'Products'],
            ['Create variable', 'web', 'Products'],
            ['Update variable', 'web', 'Products'],
            ['Delete variable', 'web', 'Products'],
            ['Read discount list', 'web', 'Discounts'],
            ['Read discount details', 'web', 'Discounts'],
            ['Create discount', 'web', 'Discounts'],
            ['Update discount', 'web', 'Discounts'],
            ['Delete discount', 'web', 'Discounts'],
            ['Delete multiple discount', 'web', 'Discounts'],
            ['Read order list', 'web', 'Orders'],
            ['Read order details', 'web', 'Orders'],
            ['Create order', 'web', 'Orders'],
            ['Update order', 'web', 'Orders'],
            ['Cancel order', 'web', 'Orders'],
            ['Delete order', 'web', 'Orders'],
            ['Delete multiple orders', 'web', 'Orders'],
            ['Export excel order list', 'web', 'Orders'],
            ['Export excel order details', 'web', 'Orders'],
            ['Print order', 'web', 'Orders'],
            ['Update order detail', 'web', 'Orders'],
            ['Delete order detail', 'web', 'Orders'],
            ['Read debt list', 'web', 'Debts'],
            ['Read transaction list', 'web', 'Transactions'],
            ['Read transaction details', 'web', 'Transactions'],
            ['Create transaction', 'web', 'Transactions'],
            ['Update transaction', 'web', 'Transactions'],
            ['Delete transaction', 'web', 'Transactions'],
            ['Delete multiple transactions', 'web', 'Transactions'],
            ['Read post list', 'web', 'Posts'],
            ['Read post details', 'web', 'Posts'],
            ['Create post', 'web', 'Posts'],
            ['Sort post', 'web', 'Posts'],
            ['Update post', 'web', 'Posts'],
            ['Delete post', 'web', 'Posts'],
            ['Delete multiple posts', 'web', 'Posts'],
            ['Read category list', 'web', 'Categories'],
            ['Create category', 'web', 'Categories'],
            ['Sort category', 'web', 'Categories'],
            ['Update category', 'web', 'Categories'],
            ['Delete category', 'web', 'Categories'],
            ['Delete multiple categories', 'web', 'Categories'],
            ['Read image list', 'web', 'Images'],
            ['Read image details', 'web', 'Images'],
            ['Create image', 'web', 'Images'],
            ['Update image', 'web', 'Images'],
            ['Delete image', 'web', 'Images'],
            ['Delete multiple images', 'web', 'Images'],
            ['Read work list', 'web', 'Works'],
            ['Read work details', 'web', 'Works'],
            ['Create work', 'web', 'Works'],
            ['Update work', 'web', 'Works'],
            ['Read work summary', 'web', 'Works'],
            ['Read local list', 'web', 'Locals'],
            ['Create local', 'web', 'Locals'],
            ['Update local', 'web', 'Locals'],
            ['Delete local', 'web', 'Locals'],
            ['Delete multiple locals', 'web', 'Locals'],
            ['Read version list', 'web', 'Versions'],
            ['Create version', 'web', 'Versions'],
            ['Update version', 'web', 'Versions'],
            ['Delete version', 'web', 'Versions'],
            ['Read expense list', 'web', 'Expenses'],
            ['Read expense details', 'web', 'Expenses'],
            ['Create expense', 'web', 'Expenses'],
            ['Update expense', 'web', 'Expenses'],
            ['Delete expense', 'web', 'Expenses'],
            ['Delete multiple expenses', 'web', 'Expenses'],
            ['Approve expense', 'web', 'Expenses'],
        ];
        foreach ($permissions as $permission) {
            Permission::create([
                'name' => $permission[0],
                'guard_name' => $permission[1],
                'section' => $permission[2],
            ]);
        }

        // Create roles and assign permissions
        $roles = [
            [1, 1, 'Super Admin', 'web', '2024-06-09 17:09:31', '2024-06-09 17:09:31'],
            [1, 2, 'Customer', 'web', '2024-06-09 17:09:31', '2024-06-09 17:09:31'],
            [1, 3, 'Sales Staff', 'web', '2024-06-09 17:09:32', '2024-08-28 17:59:27'],
            [1, 4, 'Warehouse Staff', 'web', '2024-06-09 17:09:32', '2024-06-09 17:09:32'],
            [1, 5, 'Store Manager', 'web', '2024-09-24 06:37:55', '2024-09-24 06:37:55'],
            [1, 6, 'Accountant', 'web', '2024-10-02 03:42:29', '2024-10-02 03:42:29']
        ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        foreach ($roles as $key => $role) {
            Role::create([
                'id' => $role[1],
                'name' => $role[2],
                'guard_name' => $role[3],
                'created_at' => $role[4],
                'updated_at' => $role[5],
            ]);
        }

        DB::table('model_has_roles')->insert([
            ['role_id' => 1, 'model_type' => 'App\Models\User', 'model_id' => 1],
            ['role_id' => 1, 'model_type' => 'App\Models\User', 'model_id' => 2],
            ['role_id' => 1, 'model_type' => 'App\Models\User', 'model_id' => 3],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 5],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 6],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 7],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 8],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 9],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 10],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 11],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 12],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 13],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 14],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 15],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 16],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 17],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 18],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 19],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 20],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 21],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 22],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 23],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 24],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 25],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 26],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 27],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 28],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 29],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 30],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 31],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 32],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 33],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 34],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 35],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 36],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 37],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 38],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 39],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 40],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 41],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 42],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 43],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 44],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 45],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 46],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 47],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 48],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 49],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 50],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 51],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 52],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 53],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 54],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 55],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 56],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 57],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 58],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 59],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 60],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 61],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 62],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 63],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 64],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 65],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 66],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 67],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 68],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 69],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 70],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 71],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 72],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 73],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 74],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 75],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 76],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 77],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 78],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 79],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 80],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 81],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 82],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 83],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 84],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 85],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 86],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 87],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 88],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 89],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 90],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 91],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 92],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 93],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 94],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 95],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 96],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 97],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 98],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 99],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 100],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 101],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 102],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 103],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 104],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 105],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 106],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 107],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 108],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 109],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 110],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 111],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 112],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 113],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 114],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 115],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 116],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 117],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 118],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 119],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 120],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 121],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 122],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 123],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 124],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 125],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 126],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 127],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 128],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 129],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 130],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 131],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 132],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 133],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 134],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 135],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 136],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 137],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 138],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 139],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 140],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 141],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 142],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 143],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 144],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 145],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 146],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 147],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 148],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 149],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 150],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 151],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 152],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 153],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 154],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 155],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 156],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 157],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 158],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 159],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 160],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 161],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 162],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 163],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 164],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 165],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 166],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 167],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 168],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 169],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 170],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 171],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 172],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 173],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 174],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 175],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 176],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 177],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 178],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 179],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 180],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 181],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 182],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 183],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 184],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 185],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 186],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 187],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 188],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 189],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 190],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 191],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 192],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 193],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 194],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 195],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 196],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 197],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 198],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 199],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 200],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 201],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 202],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 203],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 204],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 205],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 206],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 207],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 208],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 867],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 3939],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4227],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4478],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4479],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4480],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4481],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4502],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4503],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4504],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4505],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4506],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4508],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4509],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4510],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4511],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4512],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4513],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4514],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4515],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4516],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4517],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4518],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4519],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4520],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4521],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4522],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4523],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4524],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4525],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4526],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4527],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4528],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4529],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4530],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4531],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4532],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4533],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4534],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4535],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4536],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4537],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4538],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4539],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4540],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4541],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4542],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4543],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4544],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4545],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4546],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4547],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4548],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4549],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4550],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4551],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4552],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4553],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4554],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4555],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4556],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4557],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4558],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4559],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4560],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4561],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4562],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4563],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4564],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4565],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4566],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4567],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4568],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4569],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4570],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4571],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4572],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4573],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4574],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4575],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4576],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4577],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4578],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4579],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4580],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4581],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4582],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4583],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4584],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4585],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4586],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4587],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4588],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4589],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4590],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4591],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4592],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4593],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4594],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4595],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4596],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4597],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4598],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4599],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4600],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4601],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4602],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4603],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4604],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4605],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4606],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4607],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4608],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4609],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4610],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4611],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4612],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4613],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4614],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4615],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4616],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4617],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4618],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4619],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4620],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4621],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4622],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4623],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4624],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4625],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4626],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4627],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4628],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4630],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4631],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4632],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4633],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4634],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4635],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4636],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4637],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4638],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4639],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4640],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4641],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4642],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4643],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4644],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4645],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4646],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4647],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4648],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4649],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4650],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4651],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4652],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4653],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4654],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4655],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4656],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4657],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4658],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4659],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4660],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4661],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4662],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4663],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4664],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4665],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4666],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4667],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4668],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4669],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4670],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4671],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4672],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4673],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4674],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4675],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4676],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4677],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4678],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4679],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4680],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4681],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4682],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4683],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4684],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4685],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4686],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4687],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4688],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4689],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4690],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4691],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4692],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4693],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4694],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4695],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4696],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4697],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4698],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4699],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4700],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4701],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4702],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4703],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4704],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4705],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4706],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4707],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4708],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4709],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4710],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4711],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4712],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4713],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4714],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4715],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4716],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4717],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4718],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4719],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4720],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4721],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4722],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4723],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4724],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4725],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4726],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4727],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4728],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4729],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4730],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4731],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4732],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4733],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4734],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4735],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4736],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4737],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4738],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4739],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4740],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4741],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4742],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4743],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4744],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4745],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4746],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4747],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4748],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4749],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4750],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4751],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4752],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4753],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4754],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4755],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4756],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4757],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4758],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4759],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4760],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4761],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4762],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4763],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4764],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4765],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4766],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4767],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4768],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4769],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4770],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4771],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4772],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4773],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4774],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4775],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4776],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4777],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4778],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4779],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4780],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4781],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4782],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4783],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4784],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4785],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4786],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4787],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4788],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4789],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4790],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4791],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4792],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4793],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4794],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4795],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4796],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4797],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4798],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4799],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4800],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4801],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4802],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4803],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4804],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4805],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4806],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4807],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4808],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4809],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4810],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4811],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4812],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4813],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4814],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4815],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4816],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4817],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4818],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4819],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4820],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4821],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4822],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4823],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4824],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4825],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4826],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4827],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4828],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4829],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4830],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4831],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4832],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4833],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4834],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4835],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4836],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4837],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4838],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4839],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4840],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4841],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4842],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4843],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4844],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4845],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4846],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4847],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4848],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4849],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4850],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4851],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4852],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4853],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4854],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4855],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4856],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4857],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4858],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4859],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4860],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4861],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4862],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4863],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4864],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4865],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4866],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4867],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4868],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4869],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4870],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4871],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4872],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4873],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4874],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4875],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4876],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4877],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4878],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4879],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4880],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4881],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4882],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4883],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4884],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4885],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4886],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4887],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4888],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4889],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4890],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4891],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4892],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4893],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4894],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4895],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4896],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4897],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4898],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4899],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4900],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4901],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4902],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4903],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4904],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4905],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4906],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4907],
            ['role_id' => 2, 'model_type' => 'App\Models\User', 'model_id' => 4908],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 2],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 236],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 832],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 867],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 3312],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 3496],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 3606],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 4499],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 4507],
            ['role_id' => 3, 'model_type' => 'App\Models\User', 'model_id' => 4629],
            ['role_id' => 4, 'model_type' => 'App\Models\User', 'model_id' => 2],
            ['role_id' => 4, 'model_type' => 'App\Models\User', 'model_id' => 236],
            ['role_id' => 4, 'model_type' => 'App\Models\User', 'model_id' => 867],
            ['role_id' => 4, 'model_type' => 'App\Models\User', 'model_id' => 3496],
        ]);
        $role_has_permissions = [];
        for ($i = 1; $i <= count($permissions); $i++) {
            $role_has_permissions[] =  ['permission_id' => $i, 'role_id' => 1];
        }
        DB::table('role_has_permissions')->insert($role_has_permissions);
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
